### ISSUE TITLE
Je obtížné vykopírovat text s kódem

### ISSUE THREAD

**Issue by honzajavorek** [PyLadiesCZ/pyladies#10]
@vasekch může nejspíš podat zprávu o tom jaký prohlížeč atd., ale je to něco na Windows. Mě na Macu ve Firefoxu to funguje OK.

**Comment by encukou** [comment]
Dilema: Má tohle být snadné?

**Comment by honzajavorek** [comment]
Aha, to mě ani nenapadlo, že to je feature :) Já si myslím, že to je zbytečné. Ty úkoly tě přece látku naučí i kdybys ji prvně vykopíroval. Stejně ji musíš pochopit. A nemít možnost udělat copy/paste ani nejmenšího kousku, to jde i proti tomu co děláš ty sám. Nebo snad píšeš vše z paměti, když se učíš něco nového?

Ostatně, snadné to je na celém zbytku internetu.

**Comment by encukou** [comment]
Máš nejspíš pravdu. Změněno.

**Comment by honzajavorek** [comment]
:+1:
