### ISSUE TITLE
ukol 2 - prilis podrobne

### ISSUE THREAD

**Issue by vasekch** [PyLadiesCZ/pyladies#12]
Toto je diskuzni issue
Mel jsem pri prochazeni ukolu z 2. srazu pocit, ze seznam ruznych erroru a operatoru je prilis encyklopedicky a tudiz nezazivny.

**Comment by encukou** [comment]
V domácích úkolech je trochu drilu, to k tomu holt patří. Ale doufám že se většinou daří dávat zajímavé příklady...
U prvního úkolu byl účel ukázat jednak jaké různé chyby jsou, takže ten úkol pak může sloužit jako referenční příručka pro 2–4. Alternativa by byla odkázat na [dokumentaci](https://docs.python.org/3/library/exceptions.html), ale to je (jako většina dokumentace) anglická hora textu; ještě nezáživnjší než první úkol. (Možná by ale bylo dobré tam ten odkaz přidat navíc; a asi nejlepší by asi bylo na dalším srazu rozdat "tahák" se seznamem chyb a odkazem na dokumentaci – to by bylo dobré všude; systém "taháků" ze kterých se postupně staví referenční příručka možná udělám na příští brněnský běh.) 

Při procházení výjimek by stálo za to se zaměřit na to, jestli pochopily jak chyby vypadají, a jestli zhruba rozumí anglickým jménům, spíš než to procházet po jednom. Stejně u operátorů – jen shrnout, ne procházet.

Možná by se hodil manuál pro kouče; případně to zatím hodit do poznámek?

**Comment by honzajavorek** [comment]
> V domácích úkolech je trochu drilu, to k tomu holt patří.

Toť otázka! :-)

**Comment by encukou** [comment]
To jo.
Každopádně doufám že drilu není tolik, že to někoho odradí nad každým podúkolem trošku přemýšlet. Třeba 13. úkol ukazuje stále nové věci, a i v 1. je zabudovaná zvláštnost hodná zapřemýšlení :)

**Comment by encukou** [comment]
Přesunuto na https://github.com/pyvec/naucse.python.cz/issues/39
