### ISSUE TITLE
Hodne matematiky v materialech

### ISSUE THREAD

**Issue by vasekch** [PyLadiesCZ/pyladies#13]
Diskuzni issue.
Ackoliv je v prvni lekci zmineno, ze matematiky nebude moc, mam pocit, ze se nam ji do materialu vloudilo docela dost.
Vim, ze se matematice nevyhneme, ale konkretne vysvetlovani funkci na sin(x) mi pripada trochu nestastne.
Vcera jsem pouzil pro vysvetlovani vypocet obvodu obdelniku, ktery myslim strasi o trochu mene, nez goniometricke funkce.

**Comment by encukou** [comment]
Počkej, myslíš v http://python.cz/pyladies/s003-looping/functions.html ?

Tam se sin v nepoužívá asi tak jako tlačítko na kalkulačce, není potřeba (zatím) vědět co dělá. Nikde žádnou velkou matematiku nevidím...
Přijde jako nejvhodnější funkce která je _přímo v Pythonu_, tj. nemusíš ji sám definovat.

**Comment by asgeirrr** [comment]
Taky mi přijde, že tohle není žádná větší zátěž. Teď mě nenapadá, co jiného používat v tomhle stadiu kurzu, protože ještě skoro nic neumějí a tyhle matematické funkce znají snad všechny.

**Comment by encukou** [comment]
Tomu, že má někdo osypky z pouhého slova `sinus`, bych materiály nepřizpůsoboval, nicméně `sin()` není optimální příklad funkce z jiných důvodů.

Je na to nová issue v novém repozitáři: https://github.com/pyvec/naucse.python.cz/issues/27
