### ISSUE TITLE
cheat sheet

### ISSUE THREAD

**Issue by vasekch** [PyLadiesCZ/pyladies#14]
Diskuzní issue.
Možná by se hodilo vytvořit cheat sheet, především to chápu jako slovníček vysvětlující divné názvy ze světa programátorů (řetězec, int, indentation, ...)
malý nástřel https://docs.google.com/document/d/1yy6LQNe9ElkZwIMbBgeQfUjTlmPvxYUrN4-8U1SyHi0/edit?usp=sharing (feel free to edit)

**Comment by encukou** [comment]
Tohle by mělo z materiálů vypadnout samo, pokud se přepíšou do rozumného formátu (který podporuje rejstříky, tj. Restructured Text, ne Markdown, cc @honzajavorek). Ale nebráním se tomu, aby to zatím vznikalo vedle.

**Comment by mnovackova** [comment]
Mně se jako pokračování po PyLadies docela osvědčil tenhle: /usr/lib/systemd/system-preset/90-default.preset

**Comment by encukou** [comment]
Eh? To nevypadá jako správný odkaz.

**Comment by mnovackova** [comment]
Za to muzou urcite nase kocky :) Porad mi opravuji kod...
Tady je ten spravny: https://perso.limsi.fr/pointal/python:memento

**Comment by encukou** [comment]
Tady se, zdá se, řeší dvě různé věci:
* Slovníček – na `naucse` se něco takového plánuje; je to načrtnuté v [poznámkách k naucse](https://docs.google.com/document/d/1T2OKMkhIDP-Ri2zmwV1S9KP4ntKh8oA03kSbpWYRvPA/edit#heading=h.ni01627g5twj)
* Tahák (angl. *cheatsheet*) – místo toho vzniká soustava taháků na https://github.com/pyvec/cheatsheets/

... a moc daleko jsme se nedostali. Zavírám. Jestli chcete pokračovat v diskuzi na některé z těch tématů a nenajdete lepší místo, otevřete prosím novou *issue* na https://github.com/pyvec/naucse.python.cz
