### ISSUE TITLE
Manuál pro kouče

### ISSUE THREAD

**Issue by encukou** [PyLadiesCZ/pyladies#15]
Manifest koučů PyLadies (PL), jak ho sepsala Terka:

> 1. Jsem tu proto, abych rozvíjel každou PL.
> 2. Hlavní kouč vede hodinu a otvírá nová témata. Vždy vysvětluji pouze to, co je aktuálně řešené (a nepředbíhám).
> 3. Pokud opravdu musím vysvětlovat něco, i když hlavní kouč mluví, šeptám, abych nerušil ostatní PL, které poslouchají.
> 4. Neustále se aktivně rozhlížím po červených papírkách, každá PL může být v nesnázích. A třeba to můžu být já, kdo jí zachrání. Nekempuji u jedné PL celý večer.
> 5. Na červené papírky (volání o pomoc) kolem sebe reaguji okamžitě.
> 6. Klávesnice každé PL je svatá a sahat na ní může pouze ona.
> 7. Řešení problému by mělo vzejít od PL, napovídáním jí pomůžu pouze krátkodobě.
> 8. Pokud si neví PL rady, snažím se jí dovést k řešení otázkami, na které si sama odpovídá.
> 9. Nepoužívám terminologii, kterou PL zatím nezná, ani nezlehčuji problémy, které řeší. Chápu, že je začátečník a pravděpodobně nemá ani technické zázemí.
> 10. Chválím PL pokaždé, když se jí povede vyřešit i sebemenší problém (dává jí to více chuti k dalšímu objevování).
> 
> Kdo by se chtěl dále rozvíjet v koučovacích dovednostech, doporučuji si projít http://coach.djangogirls.org/tips/index.html (je to jedná stránka).

**Comment by honzajavorek** [comment]
Asimilováno jako Markdown dokument [sem](https://github.com/PyLadiesCZ/documents/blob/master/beginner-course/coach-manifest.md).

**Comment by encukou** [comment]
Je to linkované z #2, není potřeba zvláštní issue

**Comment by honzajavorek** [comment]
Opravdu jsi myslel #2? 👀

**Comment by encukou** [comment]
Jo, https://github.com/PyLadiesCZ/documents/blob/master/beginner-course/coach-manifest.md je linkované z https://github.com/PyLadiesCZ/Documents/issues/2
