### ISSUE TITLE
Přidat zvýraznění syntaxe

### ISSUE THREAD

**Issue by tomasbedrich** [PyLadiesCZ/pyladies#22]
Přidat do příkladů zvýraznění syntaxe – napomůže pochopení, co jsou klíčová slova, co výrazy, operátory, jména funkcí, ...

**Comment by asgeirrr** [comment]
@encukou vím, že jsi chtěl řešení bez JavaScriptu, ale myslím, že pouze v CSS to ani nejde udělat, ne? StackOverflow používá např. tohle https://github.com/google/code-prettify

**Comment by tomasbedrich** [comment]
Nevím, jak to nasazuješ, ale můžu zmínit např. [Pygments](http://pygments.org/) – pokud máš možnost to tím prohnat nějak automaticky.

**Comment by encukou** [comment]
Dlouhodobý plán je přepsat to do ReSTu, kde jdou Pygments zapnout automaticky.

**Comment by jirutka** [comment]
Uh, lepší by bylo použít [AsciiDoc](http://asciidoctor.org/docs/user-manual/), aby to dokázal editovat také někdo jiný než pythonisté… (zvýrazňování syntaxe to umí také implicitně)

**Comment by encukou** [comment]
Viz https://github.com/pyvec/naucse.python.cz/issues/23
