### ISSUE TITLE
Jak na ty zatracené Windows… terminál, shell, git

### ISSUE THREAD

**Issue by jirutka** [PyLadiesCZ/pyladies#23]
Před nějakou dobou jsem sepsal podrobný návod, jak na Windows nastavit alespoň trochu funkční prostředí – použitelný terminál, bash, editor, git, ssh – [How to use terminal on Windows without going crazy…](https://gist.github.com/jirutka/99d57c82fa8981f56fb5) Už pomohl spoustě lidem.

Co z něj vyjít a upravit ho speciálně pro PyLadies (přeložit do češtiny, přidat instalaci Pythonu)?

**Comment by encukou** [comment]
To zní dobře :)
V Brně už máme instalaci za sebou, takže já se k tomu dostanu minimálně za půl roku.
ConEmu vypadá z toho článku dobře; snad funguje i v praxi.
A ještě bych poprosil o záměnu Sublime třeba za Atom, ať je dál všechno open-source :)

**Comment by encukou** [comment]
Přesunuto na https://github.com/pyvec/naucse.python.cz/issues/40
