### ISSUE TITLE
New web Pyladies.cz

### ISSUE THREAD

**Issue by SvetlanaM** [PyLadiesCZ/pyladies#25]
Hlavné funkcie:
a. Domov
b. Udalosti
c. Materialy
d. Lektori?
1. Úvodná stránka

a. Zobraziť informácie o PyLadies
b. Zobraziť navrchu banner s najbližšie konajúcou sa registráciou/hodinou? - možnosť presmerovať sa do detailu kurzu, kde budu už všetky hodiny, materialy, atd..
c. Zoznam – kedy sa konajú, dátum, čas, miesto , odkaz na material
d. Odporucania alebo pozitivne pribehy dievčat, ktore absolvovali pyladies (opis toho čo im to dalo a naučilo ich to)
e. Nieco ako call to action - start with python a presmerovanie na stranku s instalaciou, kde sa vyberie z troch boxov (Windows, Linux, Mac OS) a pod tym bude vzdy detailny postup pre instalaciu
f. Možnosť stať sa lektorom
1. Udalosti (hodiny)
   a. Vyber mesta
   b. Info otom, kde a kedy sa kona najblizsia
   c. Starsie hodiny + materialy
   d. Ak je mozne sa registrovat (registracia)
2. Materialy
   a. Možno by som dala ako to býva na heroku , tutorial na to ako začať s pythonom, čo si nainštalovať, niečo ako first step, ako ma django tiež, ale neviem, či tam ma python toho až tak vela okrem stiahnutia suboru a idle čo by stalo za to.
   b. Zoznam materialov podla hodin
3. Footer 
   a. Kontaktné informácie
   b. Odkaz na diskusnú skupinu (FB, Google Group)
   c. Odkaz na socialne siete, web (fb skupina, pyvec...)
4. Udalosti – zoznam všetkých podla miest (Praha, Brno, Ostrava?,...)
5. vyber mesta a pod tym info o mieste, case konania, moznost kontaktovat hlavneho organizatora, a pod tym zoznam lekcii jednoducho a rychlo dostupnych s grafickym oznacenim checkboxoch co sme uz presli ako ma napriklad Angular -- https://thinkster.io/a-better-way-to-learn-angularjs (myslim checkboxy)
6. Materialy – zoznam všetkých materiálov a domacich uloh

**Comment by encukou** [comment]
Je to spíš tak, že máme obsah co je na stránkách teď. To ostatní by mělo být jednoduché přidat, až to někdo sepíše :)

**Comment by SvetlanaM** [comment]
spisat mozem, len mi slo skor o to rozlozenie, ci teda za vas moze byt ze na uvodnej stranke, na podstrankach atd

**Comment by encukou** [comment]
Těžko říct; takhle z odrážek si těžko představím jak to nakonec bude vypadat. Myslím že by bylo dobré udělat jednoduchý nástřel, který by se pak dal dál jednoduše upravovat.

To hlavní co mi chybí v těchhle odrážkách je, že PyLadies srazy nejsou jenom kurz. V Brně jsou srazy s individuálním programem (vlastní projekty, dodělávání úkolů, kurz pro ty co nemohly přijít v pondělí, atd.). V Praze doufám, že to za nějakou dobu bude podobné. PyLadies jsou _komunita_, ne _začátečnický kurz_.

---
1. Úvodná stránka
   a. Zobraziť informácie o PyLadies
   b. Zobraziť navrchu banner s najbližšie konajúcou sa registráciou/hodinou? - možnosť presmerovať sa do detailu kurzu, kde budu už všetky hodiny, materialy, atd..
   - Tady je problém s tím, že PyLadies konají v různých městech, a jsou různé druhy akcí (kurz, srazy). Odkaz na jednu nejbližší by nebyl užitečný pro všechny.
   - Plus, bude to možné jednoduše aktualizovat? Nechci další místo (po FB a mailu) kam bude potřeba každý týden něco psát.
   
   c. Zoznam – kedy sa konajú, dátum, čas, miesto , odkaz na material
   d. Odporucania alebo pozitivne pribehy dievčat, ktore absolvovali pyladies (opis toho čo im to dalo a naučilo ich to)
   - "Absolvovat PyLadies" nedává moc smysl; absolvovat jde kurz, který se v rámci PyLadies organizuje. Takže tady by spíš měly být dojmy děvčat, které jsou v PyLadies aktivní.
   
   e. Nieco ako call to action - start with python a presmerovanie na stranku s instalaciou, kde sa vyberie z troch boxov (Windows, Linux, Mac OS) a pod tym bude vzdy detailny postup pre instalaciu
   - Call to action by měl být "přijďte na straz/přihlašte se na kurz". Zrovna instalaci je nejlepší dělat na sraze. A projít kurzem doma sice jde, ale není to účel PyLadies.
   
   f. Možnosť stať sa lektorom
   - koučkou/koučem
2. Udalosti (hodiny)
   - "Události" nebo, ještě líp, "Srazy". "Hodiny" ne, pokud teda tohle nemá být sekce jen pro ten začátečnický kurz
   
   a. Vyber mesta
   - myslím že se zatím všechny města vejdou na jednu stránku, není potřeba klik navíc
   
   b. Info otom, kde a kedy sa kona najblizsia
   c. Starsie hodiny + materialy
   d. Ak je mozne sa registrovat (registracia)
3. Materialy
   a. Možno by som dala ako to býva na heroku , tutorial na to ako začať s pythonom, čo si nainštalovať, niečo ako first step, ako ma django tiež, ale neviem, či tam ma python toho až tak vela okrem stiahnutia suboru a idle čo by stalo za to.
   - Materiály jsou hotové, nemyslím si že někdo bude dělat nějaké další :)
   
   b. Zoznam materialov podla hodin
4. Footer
   a. Kontaktné informácie
   b. Odkaz na diskusnú skupinu (FB, Google Group)
   c. Odkaz na socialne siete, web (fb skupina, pyvec...)
   - každé město má jiné kontakty i skupiny

**Comment by asgeirrr** [comment]
Neměl jsem zatím čas to detailně projít, ale co mě napadlo při zběžném čtení:

2.f. **Možnost stát se koučem** -- kromě informací o tom, co to obnáší, bych tam přidal desatero pro kouče, které máme tady na GitHubu. Teď jsme měli v úterý nového kouče a docházelo ke stejným problémům, které jsou právě v tom desateru, tak bych s tím kouče seznamoval co nejdřív.

4.c. **Odkaz na socialne siete, web** -- Myslím, že není problém dát tam odkaz na 2 FB skupiny, 2 Google Groups a stránku python.cz, kde je přehledná mapa nadcházejících srazů.

Ad **materiály** -- všechno bych držel v jednom GitHub repozitáři, jak to máme teď včetně nějakých tematických hodin a srazů, které probíhají po začátečnickém kurzu. Takže myslím stačí odkaz na ty materiály.

Přesně jak píše Petr, akcentoval bych to, že PyLadies nejsou _jen_ začátečnický kurz. Myslím, že by to chtělo přitáhnout i holky, které už umí programovat a nepotřebují vyloženě začátečnický kurz, ale spíš poradit s nějakým vlastním projektem. Mohou se zapojit i holky, které umí v jiném jazyce a zajímá je Python a tempo začátečnického kurzu by pro ně bylo příliš pomalé a chtěly by spíš rychlokurz Pythonu ideálně od někoho, kdo umí také ten jazyk, který znají ony. Něco typu "Zajímá tě konkrétní téma? Máš vlastní projekt, se kterým potřebuješ poradit nebo ke kterému sháníš další lidi? Napiš na FB nebo GG a uvidíme." (hrozná formulace, já vím, ale něco v tom stylu).

**Comment by asgeirrr** [comment]
d. **Lektoři** -- možná to není špatný nápad, dát tam pár obrázků lidí a odkazy na jejich profily na GitHubu a Twitteru atd. něco jako měl PyCon viz https://cz.pycon.org/2015/talks/ Ale neměli by to být jen lektoři, spíš členové komunity.

A takový divoký nápad, mohla by to být taková "prestižní" odměna pro lidi, kteří udělají pro PyLadies něco navíc, pojmout to trochu jako Hall of Fame.

**Comment by SvetlanaM** [comment]
Dakujem, zapracujem Vase poznamky. 

no mozno by som vychadzala z mojho prveho dizajnoveho navrhu s tym ze texty budu o 100% ine a mozno upravene niekde call to action.
![pyladies](https://cloud.githubusercontent.com/assets/3219358/11268437/106138ca-8eb1-11e5-8b82-af82b7e64bc4.png)

**Comment by lspdv** [comment]
Ja bych chtela avizovat, ze od dalsiho behu budeme mit i podporovatele/sponzory, coz vlastne mame uz ted - na prostory - a jiste by bylo fajn, aby meli svoji kolonku na strance?? Slo by to prosim?

**Comment by encukou** [comment]
No jo, sponzoři by tam asi měli být. Většinou mívají sekci na hlavní stránce; viz [cz.pycon.org](http://cz.pycon.org/2015/). Za Brno jsou to Red Hat a Experis; někde poblíž by měl být i pyvec.

**Comment by SvetlanaM** [comment]
anos partnermi ratam :)

**Comment by honzajavorek** [comment]
Přesouváme se s webem na https://github.com/PyLadiesCZ/pyladies.cz/issues, jo?

**Comment by lspdv** [comment]
Joo :-)

Odesláno z iPadu
1. 1. 2016 v 12:16, Honza Javorek notifications@github.com:
