### ISSUE TITLE
Háčky a čárky ve Windows

### ISSUE THREAD

**Issue by zuzejk** [PyLadiesCZ/pyladies#28]
Ahoj,
ve vzorových příkladech v materiálech jsou háčky a čárky, ale ve windows to samozřejmě vyhodí chybu - to přidělává zbytečné zdržení při práci, když se to pak písmenko po písmenku opravuje. Nebylo by tudíž lepší nepoužívat v řešených příkladech diakritiku?

**Comment by encukou** [comment]
Tohle by se mělo vyřešit v #23, nebo jsem slyšel že diakritiku umí věc zvaná PowerShell. Chce to zkonzultovat s nějakým odborníkem na Windows, ale takové lidi já moc neznám :(

**Comment by jirutka** [comment]
Jop, #23 by to mělo řešit. Pokusím se k tomu tento týden dostat.

**Comment by encukou** [comment]
Python 3.6 tohle řeší.

Nová issue v novém repozitáři: https://github.com/pyvec/naucse.python.cz/issues/28
