### ISSUE TITLE
Najít knihovnu na hudbu

### ISSUE THREAD

**Issue by encukou** [PyLadiesCZ/pyladies#29]
Existuje _jednoduchá_ knihovna na přehrávání not (`melodie = ['C', 'E', 'G'] * 2 + ['E', 'E', 'D', 'E', 'F', 'D'] * 2 + ['E', 'D', 'C']; play(melodie)`), která by fungovala na všech systémech?

**Comment by honzajavorek** [comment]
Wow, tohle by bylo super! @zuzejk by si mohla k hudebním nástrojům, které ovládá, přidat Python :smile: :guitar:

**Comment by jirutka** [comment]
Co třeba [PySynth](http://mdoege.github.io/PySynth/)? Nezkoušel jsem ji, ale podle popisu to vypadá slibně.

**Comment by encukou** [comment]
Přesunuto na https://github.com/pyvec/naucse.python.cz/issues/36
