### ISSUE TITLE
32bit / 64bit Windows

### ISSUE THREAD

**Issue by honzajavorek** [PyLadiesCZ/pyladies#3]
Jak to zjistit a proč to zjišťovat? Nejlépe se screenshotem.

`Start > Control Panels > System and Security > System`

nebo

`Start > pravý klik na Počítač > Properties > hodí nás to na tutéž stránku jako postup výše`

Co a jak na Windows 8?

**Comment by asgeirrr** [comment]
Ten popis, co jsem přidal v PR funguje i na Windows 8, i když je tam i jiná cesta v tom novém Metro nastavení.
