### ISSUE TITLE
Dát do lekce o Gitu .gitignore

### ISSUE THREAD

**Issue by encukou** [PyLadiesCZ/pyladies#31]
Mac dělá soubory .DS_Store, které je potřeba vyfiltrovat.

**Comment by jirutka** [comment]
Zároveň tam doporučuji přidat zmínku o globálním `.gitignore`, aby to pak zbytečně necpali do každého repositáře.

**Comment by encukou** [comment]
Přesunuto na https://github.com/pyvec/naucse.python.cz/issues/35
