### ISSUE TITLE
Gitový tahák - git add $SOUBOR

### ISSUE THREAD

**Issue by encukou** [PyLadiesCZ/pyladies#32]
Je tam jen `git add`, což je matoucí, chce to celé `git add SOUBOR`.
Nezapomeň aktualizovat obrázek z taháku v materiálech.

**Comment by jirutka** [comment]
Technicky vzato je to přinejmenším neúplné, `git add` přijímá glob…

**Comment by encukou** [comment]
`git add` toho přijímá! Ale [`man git add`](https://git-scm.com/docs/git-add) se holt na tahák nevejde :)
`git help` by tam mohl být zmíněný.

**Comment by encukou** [comment]
Přidáno v https://github.com/pyvec/cheatsheets/commit/dea90761b31fd6759ebbe5958e403342985f0c6f
