### ISSUE TITLE
Git bash místo Windows terminálu

### ISSUE THREAD

**Issue by encukou** [PyLadiesCZ/pyladies#34]
Možná bude lepší standardizovat příkazovou řádku

**Comment by jirutka** [comment]
:+1: Souvisí s #23.

**Comment by encukou** [comment]
Python 3.6 by měl umět Unicode ve windowsí konzoli. V nových Windows je Ubuntu.

Stávající technologie nám to usnadňují rychleji než stačíme zkoušet nové :)

**Comment by jirutka** [comment]
V nových Windows _není_ Ubuntu. Je v nich Windows Subsystem for Linux, který se více či méně snaží "emulovat" Linux, a tedy je možné na nich nainstalovat některé balíčky z repositářů Ubuntu.

Nedávno jsem to zkoušel kvůli Ruby a pár gemům s nativním rozšířeními a dost pohořel. Narážel jsem na chyby/nedostatky ve WSL. Python jsem na tom nezkoušel.

**Comment by encukou** [comment]
Jde spíš o terminál, bash, ssh, možná git

**Comment by benabraham** [comment]
Jedno další mínus Bash for Windows je i ten, že instalace je poměrně komplikovaná.
