### ISSUE TITLE
Používat -m

### ISSUE THREAD

**Issue by encukou** [PyLadiesCZ/pyladies#36]
Místo `pip` používat `python -m pip`, místo `py.test` používat `python -m pytest`. Vždycky se najde jedna nebo dvě PyLadies, kterým zkratka nefunguje :(

**Comment by honzajavorek** [comment]
Mě by zajímalo, proč to nefunguje. To je nějaký bug? Vždyť je naučíme něco,
co v reálu nikdo nedělá :(

**Comment by encukou** [comment]
Mně by taky zajímalo proč se to děje. Příště to zkusím zjistit, ale ono dlouhé debugování na počítači jedné z PyLadies zdržuje všechny ostatní :(

**Comment by asgeirrr** [comment]
Nestačilo by dát poznámku do materiálů "Pokud ti to nefunguje, použij
příkaz X?" Je to nešikovné, vím, ale mě se zdá, že je lepší než všechny
učit používat python -m pip...

Dne St, 16. prosinec 2015 v 11:13 h uživatel Petr Viktorin napsal:

> Mně by taky zajímalo proč se to děje. Příště to zkusím zjistit, ale
> ono dlouhé debugování na počítači jedné z PyLadies zdržuje všechny
> ostatní :(
> 
> — Reply to this email directly or view it on GitHub[1].

Links:
1. https://github.com/PyLadiesCZ/pyladies/issues/36#issuecomment-165056191

**Comment by encukou** [comment]
To je taky možnost.

**Comment by jirutka** [comment]
To je jednoduché, zřejmě mají špatně nastavenou PATH.

**Comment by encukou** [comment]
Jo, venv\Scripts\activate.bat jim zřejmě špatně nastavuje %PATH%.

**Comment by lspdv** [comment]
Muze to byt proto, ze kdyz se instaloval python, tak se tam ve windows melo nekde zatrhnout neco o ceste path. Ale v materialech to bylo napsano trochu pozde a par holek to pri instalaci nezatrhlo?? To vim ze se nam tak stalo asi u dvou. Pokud to muze tim, tak mam navrh. Opravdu tucne v instalaci tento bod zvyraznit. Aby se na to nezapominalo. Jestli to proto neni a jsem mimo, tak se omlouvam. 

Odesláno z iPadu
1. 12. 2015 v 12:11, Petr Viktorin notifications@github.com:

**Comment by encukou** [comment]
To je rozumný odhad. U dvou – to by na Prahu sedělo! Ale aktivace venvu by to stejně měla přidat :(

**Comment by jirutka** [comment]
Měla, ale bavíme se tu o fundamentálně rozbitém systému (Windows), takže je "normální", že věci nefungují jak by měly, v závislosti na aktuální konstelaci hvězd, aktivitě slunce... ;)

**Comment by encukou** [comment]
@jirutka, to je nám všem jasné; nemyslím že tvůj příspěvek byl kostruktivní.

**Comment by jirutka** [comment]
Ok, sry, smažu ho.

**Comment by asgeirrr** [comment]
@lspdv nejsem si jist, že je to tímhle, každopádně přidání Python binárky na path ve Windows jsem stihl udělat na PyConu spolu s tím, jak zjistit verzi Windows a už je to i zmergované do materiálů, viz http://pyladies.cz/v1/s001-install/instalace.html.

**Comment by encukou** [comment]
Diskuse na FB: https://m.facebook.com/groups/1640052339543471?view=permalink&id=1702312753317429

**Comment by lspdv** [comment]
já bych tedy v materiálech v částech ve kterých ještě zmíňka o používání -m, udělala poznámku, pokud to bez nefunguje, aby zkusily s -m..... jak tak koukám na četnost těch příkazů v materiálech, tak je to asi ve 3 lekcích. souhlas @encukou?

**Comment by encukou** [comment]
Radši bych to všechno přepsal na `python -m` – tak to bude fungovat všude. Říkat lidem "Pokud to nefunguje, udělej X" funguje když je jeden takový problém, ale když jsou třeba 3 najednou, je to horší :)

**Comment by encukou** [comment]
Teď jsem na to narazil, tak jsem to změnil všude. Snad to takhle bude stačit :)
