### ISSUE TITLE
adresář vs. složka

### ISSUE THREAD

**Issue by honzajavorek** [PyLadiesCZ/pyladies#4]
Lidi podle mě moc neznají slovo "adresář" v počítačovém kontextu a je dobré říct, že to je "složka", což zná každý. Je ale fajn zmínit, že složka je folder, adresář je directory a že příkazy v řádce tudíž mají nějaký význam - "change directory", "remove directory", "make directory", atd. Není to pak taková magie.

**Comment by encukou** [comment]
Možná by tohle mohla vzít @Lspdv ?
