### ISSUE TITLE
Ilustrovat lekce

### ISSUE THREAD

**Issue by honzajavorek** [PyLadiesCZ/pyladies#45]
K nápadu mě přivedl následující tweet:

[<img width="584" alt="screen shot 2016-02-27 at 14 11 52" src="https://cloud.githubusercontent.com/assets/283441/13373020/177621ee-dd5c-11e5-977e-a34824b94409.png">](https://twitter.com/jay_gee/status/702638177471873024)

Neříkám, že bych to měl ilustrovat já, neříkám, že bych to neměl ilustrovat já. Je to asi hlavně o času a nápadech. Pokud by se toho chopila nějaká účastnice, bylo by to fajn :art:

**Comment by encukou** [comment]
Přesunuto na https://github.com/pyvec/naucse.python.cz/issues/34
