### ISSUE TITLE
Atom - info o odsazování je matoucí

### ISSUE THREAD

**Issue by lspdv** [PyLadiesCZ/pyladies#49]
Zkusím to tu krátce popsat po reakci jedné pražské PyLady. Dělala si první lekci doma a psala nám, že nechápe jestli má odsazování v Atomu správně. V materiálech je obecný popis 2 řádky o odsazování a poté info ke každému editoru zvlášť. 

Pokud to dobře chápu - editor Atom jsem nikdy nepoužívala - chová se trochu jinak než ostatní editory - není v něm potřeba mezery nastavovat, nicméně v tom případě se jeho chování trochu neslučuje s obecným popisem prvních dvou řádků, který je pro ostatní editory. Jelikož, když se dá v Atomu šipka doleva, tak to jsou 4 mezery, ale poskočí to o TAB rovnou, ale jsou to 4 mezery!! v obecném popisu ale ujišťujeme, že pokud to poskočilo o TAB, tak to 4 mezery nejsou a je nutno aby byly. A to je matoucí!

Proto by bylo asi lepší u Atomu doplnit větu o tom, že v něm se zkouška s šipkou doleva nedá použít jako u ostatních.

Ráda přidám pull request až mi někdo potvrdí, že je tento postup správný. Možná jsem úplně mimo, ale zkoušely jsme to Verčou ve vlaku na 4 editorech a pochopily z toho, že Atom je tedy ve zkoušce s šipkou doleva vyjímka???

:snake: dík za reakci!

**Comment by encukou** [comment]
Teď nemám nainstalovaný Atom a asi se k tomu dnes nedostanu :( Jestli se k tomu někdo dostane dřív, tady je co bych zkusil:
- Je potřeba uložit ten soubor s příponou `.py`
- Dají se jednotlivé mezery vybrat myší? Jestli jo, tak je potřeba v materiálech nahradit test se šipkou doleva tímhle.

**Comment by lspdv** [comment]
ahaa. jdu to zkusit. přípona .py proběhla

Dne 7. dubna 2016 13:43 Petr Viktorin notifications@github.com napsal(a):

**Comment by lspdv** [comment]
Nedají se vybrat mezery myší. Vybere to celý TAB. A i když udělám 4 mezery,
tak mi to nejde vybrat myší jako mezery. Atom jsem stáhla a nainstalovala,
nic nikde neměnila jak bylo v tutoriálu. jsem z OSX a ne z Windows.

Zajimavé na tom je, že Verče co byla na minulém běhu to funguje stejně.
Takže pokud je to takto špatně, mají to pravděpodobně špatně všechny

Dne 7. dubna 2016 15:00 Veronika Gabrielová gabrielova.veronika@gmail.com
napsal(a):

**Comment by encukou** [comment]
A sakra. Takže se to nakonec musí někde nastavovat. Asi jsem to zkoušel s už nějak nastaveným Atomem :(

**Comment by lspdv** [comment]
Noo, zkusím to vypátrat :-)

2016-04-07 15:19 GMT+02:00 Petr Viktorin notifications@github.com:

**Comment by SvetlanaM** [comment]
ja robim s atomom, sice som to necitala cele co riesite ale v nastaveniach su k tomu moznosti ak riesite kolko je to medzier. Co znamena toto? Nedají se vybrat mezery myší. Vybere to celý TAB. 
<img width="1280" alt="snimek obrazovky 2016-04-07 v 19 54 38" src="https://cloud.githubusercontent.com/assets/3219358/14361397/ebf300aa-fcfa-11e5-8bc6-9a2b26e48f68.png">

**Comment by encukou** [comment]
OK, dopíšeš prosím do materiálů jak nastavit odsazování čtyřmi mezerami?

**Comment by SvetlanaM** [comment]
ja? ale po mne to musia vetsinou cesky opravit. Ale mozem dopisat

**Comment by lspdv** [comment]
tak napiš mi to po slovensky a já to přepíšu.

Já spíš furt nechápu, jaký je mezitím rozdíl, když to tedy holky možná
celou dobu používaly špatně a funguje to :-)) ale bude lepší to opravit!!
Já bych to mohla psát až ve chvíli, když bych chápala proč :-)))

2016-04-07 20:07 GMT+02:00 Svetlana notifications@github.com:

**Comment by honzajavorek** [comment]
Není to tak, že to prostě Atom dělá ve výchozím nastavení tak jak chceme,
jen to nejde snadno zjistit, protože se to tváří jako tab?

**Comment by SvetlanaM** [comment]
ja som nikdy nic nemenila, mne to takto slo od prvej instalacie...ja som stale nepochopila co ona na tom fb pisala vlastne...

**Comment by lspdv** [comment]
Ona je zmatena (jestli to chapu jejima ocima spravne) z tutorialu, kde je psano dej sipku doleva a posune se to o jednu mezeru i kdyz jsi puvodne odsadila TAB. Tak se to deje ve vsech editorech, jen v Atomu ne a proto ji to asi mate. 

Odesláno z iPadu
1. 4. 2016 v 23:26, Svetlana notifications@github.com:

**Comment by asgeirrr** [comment]
Jako kontrola by stačilo zapnout zvýraznění bílých znaků, pak holky uvidí, že po zmáčknutí tabu uvidí 4 tečky, když to jsou mezery a dva zobáčky, když je to tab. Je to v Edit > Preferences > Show Invisibles. Skoro až dole.

**Comment by zuzejk** [comment]
My jsme to teďka kontrolovali přes poznámkový blok a ukládá to jako 4 mezery. Z toho všeho vyplývá, že atom je po stažení přednastavený správně, takže se nemusí kontrovat vůbec.

**Comment by lspdv** [comment]
Dobra s tim souhlasim, ale o co tu jde je, ze mame v materialech instrukce, ktere slecny matou v kontrole. Je potreba tedy k Atomu dopsat vetu o tom, ze se chova trochu jinak a kontrola s sipkou doleva (ktera je popsana v obecne casti) na nej neplati?!!!

;-) 

Odesláno z iPadu
1. 4. 2016 v 8:24, zuzejk notifications@github.com:

**Comment by honzajavorek** [comment]
Ja bych tam dopsal, ze Atom se proste nastavovat nemusi a ze se chova
spravne i presto, ze kontrola sipkou je u nej neucinna. Ultimatni kontrola
je pres poznamkovy blok, ale tim je to asi zbytecny komplikovat.

2016-04-08 9:22 GMT+02:00 Veronika notifications@github.com:

**Comment by lspdv** [comment]
Jo! Dobrá! Je důležité nikoho nemást. Já su z toho taky zmatená. :-)

Všem zůčastněným děkuji za pomoc!!!!

Dne 8. dubna 2016 9:25 Honza Javorek notifications@github.com napsal(a):

**Comment by lspdv** [comment]
Poslala jsem pull request, děkuji všem zúčastnění, zvolila jsem pro holky kontrolu pomocí 4 teček při nastavení Show Invisibles.
