### ISSUE TITLE
Co je to virtualni prostredi a proc ho mam pouzivat?!

### ISSUE THREAD

**Issue by lspdv** [PyLadiesCZ/pyladies#51]
Bylo mi divne, proc se me na to vcera, s odstupem casu po instalacich zeptalo par slecen s opravdu nechapavym vyrazem a pote, kdyz jsem na to odpovidala do tretice na facebooku, tak jsem se sla ujistit, ze to je v materialech popsane. Ale neni tam o tom ani zminka. Je to zamerne? Jakoze si to ma slecna vygooglit sama? :-) pokud to neni zamer, muzu pro to zkusit neco udelat? 

Vypada to, ze zpusob, kterym jsem to vysvetlila ve vlaknu na facebooku pomaha slecnam pochopit k cemu jim to je ;-)

**Comment by encukou** [comment]
Záměr to není. Jestli chceš, můžeš to dopsat [tady](https://github.com/PyLadiesCZ/pyladies.cz/blob/master/original/v1/s001-install/instalace.html) :)
Nebo to můžu sepsat já, ale dostanu se k tomu až později.

**Comment by lspdv** [comment]
Dobra :-) rada zkusim prilozit ruku k dilu ac nejsem tak dobry spisovatel jako Ty ;-) 

Odesláno z iPadu
1. 4. 2016 v 11:07, Petr Viktorin notifications@github.com:

**Comment by honzajavorek** [comment]
Spisovatelstvi neni v genech, to je praxi nabyte remeslo! :-P
