### ISSUE TITLE
Úkoly 2 - operátor @

### ISSUE THREAD

**Issue by encukou** [PyLadiesCZ/pyladies#6]
Od Pythonu 3.5 bude `@` operátor. Úkol by měl použít něco co se nebude lišit mezi verzemi.
(případné dát `$` i `@`?)

**Comment by honzajavorek** [comment]
S @vasekch jsme nějak nepřišli na to, jaký má v tom příkladu vlastně ten `@` pedagogický význam.

**Comment by encukou** [comment]
Hm, čím víc přemýšlím jak to vysvětlit, tím víc mi taky připadá že by to tam být nemuselo.

A ke zbytku úkolu, na to že SyntaxError vznkne při kompilaci ale TypeError až za běhu asi stejně nikdo jen tak nepřijde :(

**Comment by honzajavorek** [comment]
Myslim ze holky urcite v teto fazi netusi co znamena pri kompilaci a co za
behu. Jsou rady ze chapou rozdil mezi konzoli, virtualenvem a splachovacim
pythonem.

2015-07-08 15:51 GMT+02:00 Petr Viktorin notifications@github.com:

**Comment by encukou** [comment]
To máš pravdu, to je terminologie jen pro tuhle issue :)
V Brně jsem jim při procházení úkolů vysvětlil že při SyntaxError Python vůbec netuší, co s tím programem má dělat – když někde chybí závorka tak si nedokáže spojit co k čemu patří, co je příkaz a co proměnná.
Až když má nějakou představu, co program jako celek znamená, tak ho může procházet řádek po řádku, a přitom můžou vzniknout ty další chyby.

Je to zbytečná znalost? Možná; na druhou stranu zase nejsme DjangoGirls, aby se možná-zbytečné znalosti osekávaly.

**Comment by jirutka** [comment]
> Je to zbytečná znalost?

IMHO naopak důležitá. Jen nechápu, jak to souvisí s operátorem `@`… Tohle lze jednoduše demonstrovat třeba na té chybějící závorce.

**Comment by zuzejk** [comment]
teď jsem objevila tohle staré issue, @ z úkolů teda raději zrušit?

**Comment by lspdv** [comment]
vubec nevim, distancuji se od tohoto rozhodnuti.

**Comment by vasekch** [comment]
@zuzejk  ano, zrušit prosím. Myslím, že to v tak úvodní fázi nemá přínos (navíc ta změna od 3.5 zmíněná nahoře). Stejnou vlastnost ilustruje v prvním úkolu "Zkusíš použít vykřičník (!) jako operátor?".

**Comment by encukou** [comment]
Zrušeno v commitu https://github.com/PyLadiesCZ/pyladies.cz/commit/b9993a4cf5ddb88b298a4b50e23d8f6803b19920
