### ISSUE TITLE
Materiály první lekce - Ubuntu on Windows 10

### ISSUE THREAD

**Issue by vasekch** [PyLadiesCZ/pyladies#61]
Dnes mi kolega ukazoval instalaci Ubuntu na Win 10.

https://insights.ubuntu.com/2016/04/14/howto-ubuntu-on-windows-2/

Co si myslíte o tom, že bychom to dali do materiálů jako možnost (nebo povinnost) pro účastnice s Win 10 používat nativní Linux shell (bash)?

Myslím, že by se tím vyřešil problém s Unicode.

**Comment by asgeirrr** [comment]
Vypadá to dost jednoduše a pomohlo by to při vysvětlování příkazové
řádky. Vysvětlovat všechno 2x je otrava a unicode problémy jsou taky na
nic. Windows by už měly mít v budoucnu normální bash, takže tímhle
bychom to jen urychlili. Ale je to zase instalace navíc, tak nevím,
jestli to nebude v hodině rušivé, když půlka holek  bude něco instalovat
a druhá ne.

**Comment by encukou** [comment]
Do dalšího běhu to možná nebude beta, a půjde to nainstalovat jednodušeji.
Do té doby bych to já nezaváděl, protože by se stejně muselo všechno vysvětlovat dvakrát, a problémy s Unicode taky budou dál, dokud nebudou všude ty nové Windows (nebo nový Python – 3.6 možná pár problémů s Win příkazovou řádkou vyřeší).

**Comment by vasekch** [comment]
@encukou souhlas, zavírám toto issue, kdyztak si později otevřeme nové
