### ISSUE TITLE
Přesunutí funkcí z lekce 3 do lekce 2

### ISSUE THREAD

**Issue by zzuzzy** [PyLadiesCZ/pyladies#63]
Chtěla jsem navrhnout diskuzi o tom, zda nepřesunout vysvětlení funkcí (argumenty funkce, pojmenované argumenty, volání funkce,  návratová hodnota) ze 3. lekce již do 2. lekce.

V tomto běhu (v Praze) Týna skončila vysvětlování 2.lekce asi o čtvrt hodinky dříve, naopak já jsem 3. lekci nestihla celou (while cyklus jsem pouze nakousla, holky si jej nestihly vyzkoušet).  Samozřejmě příčina mohla být v tom, že jsem nesledovala správně čas, příliš se věnovala domácím úkolům, ale z poznámek z minulého běhu jsem se dočetla, že ani Vašek ten while cyklus nestihl.

Proto bych navrhla vysvětlit obecně, co je to funkce a její argumenty už v 2.lekci. 3. hodinu pak věnovat přetypování, randrange a hlavně těm cyklům, které jsou těžké na pochopení a vyzkoušení. Tenhle případný přesun by neměl mít dopad na nutnost revidovat domácí úkoly, protože úkoly (pardon projekty:-)) z 3.lekce se věnují především procvičení cyklů.
@encukou @vasekch @asgeirrr @Aprillion co vy na to? Dávalo by to smysl?

**Comment by encukou** [comment]
No, 2. lekce se už teď neprobírá celá na srazu, poslední kousek je odkázán z úkolů. Možná by se to samé mělo udělat s whilem, místo přesouvání funkcí?

Mně se funkcema se dobře začíná, takže pro Brno bych je rád nechal na začátku.

**Comment by lspdv** [comment]
Muze to byt samozrejme specificke pro Prahu. Tak asi je dulezite co na to
Vasek, Oskar a dalsi

Dne 4. října 2016 22:27 Petr Viktorin notifications@github.com napsal(a):

**Comment by encukou** [comment]
Jinak ani případné přesouvání domácích <s>úko</s>projektů by neměl být problém.

**Comment by asgeirrr** [comment]
@zzuzzy vím, že @vasekch dopadl minulý běh stejně, while cyklus zbyl na
další lekci. Na druhou stranu to nebyl problém, protože potom byl Git a
ten je taky o trochu kratší. Proti tomu přesunu nic nemám, protože se
stejně od začátku používají funkce, jen nevědí, co to je:) Bude vypadat
líp, když nebudou obsahy lekcí přetékat do dalších.

**Comment by lspdv** [comment]
Rozhodne souhlasim z pripadnym presune, ktery muze byt specificky pro Prahu.

Jestli tomu dobre rozumim, znamenalo by to akorat upravit praha.yml? Matrialy jsou nakouskovane dobre ne?

@vasekch a @asgeirrr, kdyby chom to stihli vyresit do konce tohoto tydne, tak Vasek ma dalsi stredu 2. lekci a pak i to 3.lekci na PyLadies v MSD, mohlo by se hned otestovat jak to funguje a necekat s tim az do jara. Nechci vas hnat, ale bylo by to prinosne!

**Comment by lspdv** [comment]
Na zkousku jsem udelala PR na MSD kurz a dnes to s Vaskem v Praze zkusime podle navrhu Zuzky

**Comment by vasekch** [comment]
Tak jsem to zkusil, ale ukazalo se, ze je treba dat vic prostoru nekterym zakladnim vecem, proto "zpatky na stromy" a funkcema zacnu na pristi hodine, tak jak to bylo v puvodnim planu. :)
Diky za napad!

**Comment by encukou** [comment]
Takže zavírám.

Jednotlivé kurzy se dál dají přizpůsobit, ale "hlavní" rozdělení na naucse měnit nebudu.

**Comment by lspdv** [comment]
To nebylo o presouvani v harmonogramu, rekla bych, ze to bylo o presunuti cele casti textu jinam

**Comment by encukou** [comment]
Můžeš to prosím upřesnit?

**Comment by lspdv** [comment]
muzu, je to vse napsane v prvnim komentari :-)

**Comment by encukou** [comment]
No, a v posledním od Vaška je zase že se to nezměnilo, tak nějak nevím na čem jste se vlastně dohodli.

**Comment by lspdv** [comment]
Tak bylo to k diskuzi v prvni rade a nemyslime si, ze jen pro Prahu.

Dne pátek 3. února 2017 Petr Viktorin <notifications@github.com> napsal(a):

**Comment by frenzymadness** [comment]
Já jsem s pořadím spokojen. Jednak díky zpětné vazbě víme, že je třeba cykly hodně procvičit a také vypouštíme Git a tak budeme mít v jedné lekci cyklus for a želvu a ve druhé while a procvičování.

**Comment by vahalova** [comment]
Zavírám, kurz si teď skládá každý sám.
